# Generated by Django 5.0.4 on 2024-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='quantidadeDisponivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidadeTotal',
            field=models.IntegerField(null=True),
        ),
    ]
