# Generated by Django 5.0.4 on 2024-05-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_livro_quantidadedisponivel_livro_quantidadetotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='quantidadeDisponivel',
            new_name='quantidade_disponivel',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='quantidadeTotal',
            new_name='quantidade_total',
        ),
    ]
