# Generated by Django 5.0.4 on 2024-05-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_livro_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
