# Generated by Django 5.0.4 on 2024-05-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_alter_livro_sinopse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade_total',
        ),
    ]
