# Generated by Django 5.0.4 on 2024-05-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0009_biblioteca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='devolvido',
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
